# Generated by Django 4.0.3 on 2022-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
                ('ht', models.CharField(max_length=30)),
                ('mgc', models.CharField(max_length=30)),
                ('entrpsNm', models.CharField(max_length=30)),
                ('chckDe', models.CharField(max_length=30)),
                ('chcklnstt', models.CharField(max_length=30)),
                ('wtsmpleDe', models.CharField(max_length=30)),
                ('chckAt', models.CharField(max_length=30)),
                ('unchckProvonsh', models.TextField()),
            ],
        ),
    ]
