# Generated by Django 4.0.3 on 2022-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='wtsmpleDe',
            new_name='wtrsmpleDe',
        ),
    ]
