# Generated by Django 4.0.3 on 2022-04-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_wtsmplede_company_wtrsmplede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='unchckProvonsh',
            new_name='unchckPrvonsh',
        ),
    ]
